package com.gomoney.capture.parser

import com.gomoney.capture.model.Confidence
import com.gomoney.capture.model.TxType
import com.gomoney.capture.storage.NormalizedTransaction
import com.gomoney.capture.storage.RawEvent

/**
 * BankParser plugin contract (contracts/parser-interface.md). Adding a bank =
 * one implementation + fixtures; capture/queue/delivery code is never touched
 * (FR-008, SC-005).
 */
interface BankParser {
    /** Display name, e.g. "MellatParser" — recorded on NormalizedTransaction.parserName. */
    val name: String

    /** Bank slug, e.g. "mellat" — recorded on NormalizedTransaction.bank. */
    val bank: String

    /**
     * Package names (notifications) and/or SMS sender IDs this parser claims.
     */
    val supportedSources: Set<String>

    /** Cheap pre-check driven by RawEvent metadata (package/sender), not text parsing. */
    fun canParse(event: RawEvent): Boolean

    /**
     * Convert a raw event into a normalized transaction or a typed failure.
     * MUST be a pure function of the event (no I/O, no clock access) —
     * fixture-testable. UUIDs and fingerprints are generated by the pipeline.
     */
    fun parse(event: RawEvent): ParseResult

    // ---- shared helpers for implementations ----

    /** True when the event came from one of this parser's sources. */
    fun sourceMatches(event: RawEvent): Boolean = event.sourcePackage in supportedSources

    /** Purity-safe base transaction: timestamps come from the RawEvent only. */
    fun draft(event: RawEvent): NormalizedTransaction = NormalizedTransaction(
        id = "",
        sourceEventId = event.id,
        source = event.source,
        bank = bank,
        accountHint = "",
        type = TxType.EXPENSE.name.lowercase(),
        amountMinor = 0,
        currency = "IRR",
        txAt = event.postedAt,
        description = "",
        rawTextRef = event.id,
        fingerprint = "",
        parserName = name,
        confidence = Confidence.HIGH.name,
    )

    companion object {
        /** Collapse whitespace, strip currency words, cap at 200 chars (§2 validation). */
        fun cleanDescription(event: RawEvent): String {
            val stripped = AmountNormalizer.stripCurrencyWords(event.text)
            val collapsed = AmountNormalizer.normalizeDescription(stripped)
            return collapsed.take(200)
        }
    }
}

/** ParseResult per parser-interface.md. */
sealed interface ParseResult {
    data class Success(val transaction: NormalizedTransaction) : ParseResult

    data class Failure(
        val reason: String, // sanitized, non-sensitive detail for errorDetail (FR-023/028)
        val confidence: Confidence, // how sure the parser WOULD have parsed it
    ) : ParseResult
}
